# Replace the text below to customize your site
site_name: Aiman Ansari - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Aiman Ansari
copyright: Copyleft 2023 "Student Name" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://aiman-ansari12.github.io/MDEF-A/
repo_url: 'https://github.com/aiman-ansari12/MDEF-A'



nav:
  - Home: index.md
  - Master project:
      - Initial ideas: project/project.md
  - Experiments with Design:
      - Design Studio 1: term1/Design_studio1.md
      - Living with your own ideas: term1/Living_with_your_own_ideas.md
      - Fundamentals of Future Making: term1/Fundamentals_of_future_making.md
      - Unpacking Technology: term1/Unpacking_Technology.md
      - Narratives I: term1/Narratives01.md
      - Atlas of Weak Signals: term1/Atlas_of_Weak_Signals.md
      - Extended Intelligence II: Term2/Extended_Intelligence_II.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://in.linkedin.com/in/aiman-ansari-23a202155/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"


theme:
  name: material
  palette:
  #316181; /* Deep teal-blue */
  features:
    - navigation.tabs    
    - navigation.tabs.sticky
    
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css

markdown_extensions:
  - attr_list